### ISSUE TITLE
Still getting problems with videoloopback for gst-launch-1.0

### ISSUE THREAD

**Issue by prithvisathiya** [umlaeute/v4l2loopback#126]
So I have already seen the other problems regarding gst-launch-1.0 feeding the output to a /dev/video0 created by the videoloopback kernel module. I am getting the internal data flow error. As others have suggested, I have tried adding the `! queue !` cap and also the `! tee !` cap, and I still get the same error. I am doing a simple mjpeg stream from my microcontroller through udp and receiving it on my Ubuntu machine. Here are the commands for sender from microcontroller:
`gst-launch-1.0 v4l2src device=/dev/video0 ! "image/jpeg,width=640,height=480,framerate=30/1" ! rtpjpegpay ! udpsink host = ip port = 8082`

and for receiver on linux:
`gst-launch-1.0 udpsrc timeout=0 port=8082 ! application/x-rtp, encoding-name=JPEG,payload=26 ! rtpjpegdepay ! tee  ! v4l2sink device=/dev/video0`

Has this been resolved yet, or a workaround? Or is there no option for gstreamer1.0 and videoloopback to be compatible?

**Comment by umlaeute** [comment]
these are supposed to be fixed with `v4l2loopback>=0.10.0`
(since you haven#t specified a version number, i'm assuming you are using an outdated module).

also you might want to decode the jpeg-stream before sending it to the `v4l2lsink`.

Finally the "internal data flow error" is very generic. You could get this error simply because the caps between two elements unrelated to `v4l2loopback` could not be negotiated.
please always include the full error (preferrably with some debugging enabled)
