### ISSUE TITLE
Compiled fine but not able to run on Raspbian Stretch (linux-headers-4.9.63-v7+)

### ISSUE THREAD

**Issue by pavangayakwad** [umlaeute/v4l2loopback#150]
I am able to compile (git source downloaded) and install successfully. However, when I run modprobe get this error: FATAL: Module v4l2loopback not found in directory /lib/modules/4.9.63-v7+

![image](https://user-images.githubusercontent.com/1834890/33064564-1ea6c438-cecc-11e7-82a1-7174d8997ee8.png)

`sudo apt get install v4l2loopback-dkmg` also ran fine and when I run modprobe get the same error mentioned above.

Any help would be greatly appreciated as I am stuck here now!

**Comment by umlaeute** [comment]
1st: please always post text instead of screenshots!

then, re-run the installation in verbose mode:

     sudo make install V=1

and check whether there *is* a `v4l2loopback.ko` file in the installation directory (something like `/lib/modules/4.9.63-v7+/extra/`).

Check the type of this file.

    find /lib/modules/ -name v4l2loopback.ko -exec file {} +

Finally check whether loading the module directly succeeds:

    sudo modprobe /lib/modules/4.9.63-v7+/extra/v4l2loopback.ko

(adjust the paths as needed)

**Comment by ashirvadz** [comment]
I've run into the same issue. 
Fixed by just running:

`sudo depmod -a`
