### ISSUE TITLE
support for very old (2.6.32) kernels

### ISSUE THREAD

**Issue by Akella8282** [umlaeute/v4l2loopback#156]
Good afternoon! What version of v4l2loopback should I install on the 2.6.32-642.15.1.el6.i686 kernel? any version produces an error when executing "make".

**Comment by umlaeute** [comment]
well, if *any* version (that is: *all* versions) produces an error, then you are probably out of luck.

however, you might also want to check out the `NEWS` section, which mentions that `0.7.1` still fixed issues with *<2.6.29*, so that version will probably run on *2.6.32* as well.

please note that such old kernel versions are not actively supported any more.
however, i'll happily accept (sane) PRs that retain legacy support.

also, if you have any success (e.g. with an old version), please post this information to this issue (to h elp others with the same problem).

in any case, i'm closing this, as it is not something that will be actively fixed.
