### ISSUE TITLE
yocto layer

### ISSUE THREAD

**Issue by mmar2228** [umlaeute/v4l2loopback#211]
Dear all,

I need a Yocto layer in order to install it in my target. I have found a lot of problems when I run "make" in my target, so I need to get the v4l2loopback module installed when I build the image and root file system.

Any help?

Thanks very much

**Comment by umlaeute** [comment]
i don't know what a "yocto layer" is and i doubt that your problem is related to `v4l2loopback` - it sounds more like a system integration problem on how to add arbitrary parts to your image.

I therefore suggest to consult the support/manual/... or your "yocto layer" provider. (feel free to convince me that this is indeed a `v4l2loopback` problem)

**Comment by mmar2228** [comment]
Sure, it is not a problem of your v4l2loopback module. It is a way to install it in a embedded system when you buid the file system. I need v4l2loopback in my target board and I would like to know if somebody caan help me.

**Comment by TopperBG** [comment]
> Sure, it is not a problem of your v4l2loopback module. It is a way to install it in a embedded system when you buid the file system. I need v4l2loopback in my target board and I would like to know if somebody can help me.

DId you manage to install it within bitbake recipe ?
