### ISSUE TITLE
unable to make file

### ISSUE THREAD

**Issue by LegendHector** [umlaeute/v4l2loopback#295]
hi there im a noob when it comes to installing could someone give me a detailed step by step to install the software here is what i get when i run "make"

(cinnamon)hector@localhost:~/Desktop/v4l2loopback-master$ make
Building v4l2-loopback driver...
make -C /lib/modules/`uname -r`/build M=/home/hector/Desktop/v4l2loopback-master modules
make[1]: *** /lib/modules/4.19.98-08060-ge70db080f730/build: No such file or directory.  Stop.
Makefile:42: recipe for target 'v4l2loopback.ko' failed
make: *** [v4l2loopback.ko] Error 2
(cinnamon)hector@localhost:~/Desktop/v4l2loopback-master$

**Comment by thomashayden** [comment]
This issue is caused because the kernel headers stored in `/lib/modules/` don't match the kernel version that you are running (compare the output of `uname -r` to the kernel headers you have in `/lib/modules/`). I just solved this issue for myself by restarting, since the kernel headers had been updated to a slightly newer version, but I was still running the older kernel version. After the restart, the two matched up and I was able to run `make`.

If a restart doesn't fix it for you, you may have to manually install the correct kernel headers, but a restart is a good first step.
