### ISSUE TITLE
Not able to generate stable video stream with python

### ISSUE THREAD

**Issue by Harriebo** [umlaeute/v4l2loopback#32]
Hello,

I am working on stream generator for my video mapping set, but I am not able to get the image steady.
I open a v4l2loopback device with python-v4l2 (http://pypi.python.org/pypi/v4l2) and generate a video stream through it based on png, so can generate live video's in my vj set and still video map them and apply effects.

Test case:
1) load v4l2loopback module
2) run python:

```
import fcntl, numpy
from v4l2 import *
from PIL import Image
height = 600
width = 634
device = open('/dev/video4', 'wr')
print(device)
capability = v4l2_capability()
print(fcntl.ioctl(device, VIDIOC_QUERYCAP, capability))
print("v4l2 driver: " + capability.driver)
format = v4l2_format()
format.type = V4L2_BUF_TYPE_VIDEO_OUTPUT
format.fmt.pix.pixelformat = V4L2_PIX_FMT_RGB32
format.fmt.pix.width = width
format.fmt.pix.height = height
format.fmt.pix.field = V4L2_FIELD_NONE
format.fmt.pix.bytesperline = format.fmt.pix.width * 4
format.fmt.pix.sizeimage = format.fmt.pix.width * format.fmt.pix.height * 4
format.fmt.pix.colorspace = V4L2_COLORSPACE_SRGB
print(fcntl.ioctl(device, VIDIOC_S_FMT, format))
img = Image.open('img/0.png')
img = img.convert('RGBA')
while True:
    device.write(numpy.array(img))
```

3) run Cheese or other v4l2 stream viewer.

The result is a proper colored and sized image, but it jumps every frame from left to right and always a little more to the left so you get a sliding and jumpy video result.
What am I doing wrong?

Best regards,

Harriebo 

ps: if you woul like to see the results check: http://www.facebook.com/vjharriebo So far the LiVES, puredate, gem video mapping setup is working greath with the v4l2 streams.

**Comment by RussellYan** [comment]
Solution of @PStanS did the trick.

Instead of specifying 'wr' for the file mode, I have to use 'w' only, otherwise "IOError: [Errno 9] Bad file descriptor" would be raised when call device.write later.

If you write frames slowly, you would see that the first frame stay in the right position, and subsequent frames have a fixed offset, so it must be some kind of buffering problem as PStanS pointed out. Although it is strange that all subsequent frames stay in the right position.
