### ISSUE TITLE
Installing inside of a Docker container - /lib/modules/4.15.0-112-generic/build: No such file or directory

### ISSUE THREAD

**Issue by AlexYiningLiu** [umlaeute/v4l2loopback#328]
I am trying to install v4l2loopback inside of a Docker container. However, when I run make the following error is encountered:

```
root@6c293c764405:/v4l2loopback# make
Building v4l2-loopback driver...
make -C /lib/modules/`uname -r`/build M=/v4l2loopback modules
make[1]: *** /lib/modules/4.15.0-112-generic/build: No such file or directory.  Stop.
Makefile:42: recipe for target 'v4l2loopback.ko' failed
make: *** [v4l2loopback.ko] Error 2
```

Is this tool not supported within a Docker container? Please let me know if otherwise. Thanks.

**Comment by umlaeute** [comment]
you should read the README first.
then install the kernel-headers matching your kernel.
since the docker-container doesn't have a kernel running on it's own, the headers will 
- either have to match the host's kernel
- or you have to specify the kernel-headers you want to build against using the `KERNELRELEASE` variable. as in:

~~~
make KERNELRELEASE=5.7.0-2-amd64
~~~


also note, that in order to *use* the v4l2loopback kernel-module, you need access to a running kernel.
since you don't have a kernel running within the container, you won't be able to load the kernel-module.
this is by design (of containers like docker).
