### ISSUE TITLE
image in virtual cam horizontaly inverted

### ISSUE THREAD

**Issue by tristansca** [umlaeute/v4l2loopback#385]
Is it possible to invert horizontaly the image because it is not right:

![stonks1](https://user-images.githubusercontent.com/63504651/100775255-06c9c500-33d1-11eb-9915-b4948acff73d.png)

please help

**Comment by umlaeute** [comment]
the answer is *no*, but i think you figured this out already.

**Comment by robertvxt** [comment]
Because the v4l2loopback module does not support this so update the solution for my case as workaround.

I'm using FFMPEG to transcode the input stream/video into the virtual camera (generated by v4l2loopback) and set AVFilter flag to `hflip`.
i.e. `ffmpeg -i $stream_url -fflags nobuffer -vf hflip -pix_fmt yuv420p -f v4l2 /dev/video0`

Hope this's useful to someone.
