### ISSUE TITLE
Cannot use obs-v4l2sink as camera in Chromium for Meet

### ISSUE THREAD

**Issue by MarkoSchuetz** [umlaeute/v4l2loopback#428]
For over a year I was using a setup with OBS feeding into v4l2loopback and that was usable as a webcam in Google Meet in Chromium. Today I noticed that Meet kept reporting camera is starting which eventually failed after some time. In the same instance of Chromium I can use the virtual camera in a separate tab in, say, meet.jit.si where it works as expected. To my surprise it also works with Google Meet in in Chrome (just not in Chromium where I used to use it all the time). This is all on Manjaro. 

Versions:
- Chromium  Version 90.0.4430.85 (Official Build) Arch Linux (64-bit)
- Chrome Version 87.0.4280.88 (Official Build) (64-bit)
- OBS 26.1.2-2
- obs-v4l2sink 0.1.0-19
- v4l2loopback-dkms 0.12.5-1

**Comment by umlaeute** [comment]
do i understand correctly that the v4l2loopback device used to work correctly in *all your usecases* and still works correctly in multiple applications including the browser you are trying to make it work, just not on one single web application with one single browser?

honestly: what makes you think that this is a `v4l2loopback` issue?

i'm closing this for now, until there is *at least some* evidence that the culprit is indeed with the module.
