### ISSUE TITLE
make[1]: *** /lib/modules/6.6.9-amd64/build: No such file or directory.  Stop. make: *** [Makefile:53: v4l2loopback.ko] Error 2

### ISSUE THREAD

**Issue by RiazullJannat** [umlaeute/v4l2loopback#589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Detail

```markdown
─$ make

++++++ To sign the  module, you must set KBUILD_SIGN_KEY/KBUILD_SIGN_CERT to point to the signing key/certificate!
++++++ For your convenience, we try to read these variables as 'mok_signing_key' resp. 'mok_certificate' from /etc/dkms/framework.conf

++++++ If your certificate requires a password, pass it via the KBUILD_SIGN_PIN env-var!
++++++ E.g. using 'export KBUILD_SIGN_PIN; read -s -p "Passphrase for signing key : " KBUILD_SIGN_PIN; sudo --preserve-env=KBUILD_SIGN_PIN make sign'

Building v4l2-loopback driver...
make -C /lib/modules/`uname -r`/build M=/home/rjannat/Documents/devlopment/v4l2loopback KCPPFLAGS="-DSNAPSHOT_VERSION='"0.13.1-19-g4824538"'" modules
make[1]: *** /lib/modules/6.6.9-amd64/build: No such file or directory.  Stop.
make: *** [Makefile:53: v4l2loopback.ko] Error 2
```

### v4l2loopback version

0.13.1-19-g4824538

### kernel version

6.6.9-amd64

### OS Version

Kali GNU/Linux/2024.1

### Which CPU are you using?

amd64/x86_64 ("64bit Intel")

**Comment by umlaeute** [comment]
to quote the [README](https://github.com/umlaeute/v4l2loopback?tab=readme-ov-file#dependencies):
> The v4l2loopback module is a *kernel module*. In order to build it, you *must* have the kernel headers installed that match the linux kernel with which you want to use the module

**Comment by umlaeute** [comment]
> ### Is there an existing issue for this?
> 
>     * [x]  I have searched the existing issues
> 


also, this is a **duplicate** of
- https://github.com/umlaeute/v4l2loopback/issues/390
- https://github.com/umlaeute/v4l2loopback/issues/328
- https://github.com/umlaeute/v4l2loopback/issues/318
- https://github.com/umlaeute/v4l2loopback/issues/300
- https://github.com/umlaeute/v4l2loopback/issues/295
- https://github.com/umlaeute/v4l2loopback/issues/275
- https://github.com/umlaeute/v4l2loopback/issues/245
- https://github.com/umlaeute/v4l2loopback/issues/240
- https://github.com/umlaeute/v4l2loopback/issues/209
- https://github.com/umlaeute/v4l2loopback/issues/162
- https://github.com/umlaeute/v4l2loopback/issues/159
- https://github.com/umlaeute/v4l2loopback/issues/42

and probably some others.
the number of issues with the same problem clearly indicate a communication problem, but I have no idea to communicate it better than to write it into the README.
also I was hoping that people would do a more thorough research in the issue database (hence the "*I have searched the existing issues*" checkbox. i understand that nobody reported the problem for your exact kernel version yet - but the problem is that there are zillions of different kernel versions, and for *each* and *all* you will need the correct kernel-headers installed.

if you have suggestion on how to improve documentation and/or the issue template so that people do not have to ask this question again and again (and again), i would be very happy to incorporate it.
